<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Zeus.Samples.Console.Iec104</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Zeus.Communications\Zeus.Communications.csproj" />
    <ProjectReference Include="..\..\src\Zeus.Hosting\Zeus.Hosting.csproj" />
    <ProjectReference Include="..\..\src\Zeus.Protocols.Iec104\Zeus.Protocols.Iec104.csproj" />
  </ItemGroup>

</Project>
